CUDA_VISIBLE_DEVICES=0 python src/train_bash.py \
    --stage rm \
    --do_train \
    --model_name_or_path /home/inair/data/llama-2-7b-hf \
    --adapter_name_or_path /home/inair/data/revision_saves/sft_essay_writing_350_gpt_35_turbo \
    --create_new_adapter \
    --dataset rm_essay_writing_350_gpt_35_turbo_simple \
    --dataset_dir data \
    --template llama2 \
    --finetuning_type lora \
    --lora_target q_proj,v_proj \
    --output_dir /home/inair/data/revision_saves/rm_essay_writing_350_gpt_35_turbo_simple_correct \
    --overwrite_cache \
    --overwrite_output_dir \
    --cutoff_len 2048 \
    --preprocessing_num_workers 16 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --warmup_steps 20 \
    --save_steps 100 \
    --eval_steps 100 \
    --evaluation_strategy steps \
    --learning_rate 1e-5 \
    --num_train_epochs 300.0 \
    --max_samples 5000 \
    --val_size 0.1 \
    --plot_loss \
    --fp16